export type TreeDataSetType = {
  title: string
  children?: TreeDataSetType[]
}

export const TREE_DATASET: TreeDataSetType[] = [
  {
    title: "India",
    children: [
      {
        title: "Andhra Pradesh",
        children: [
          { title: "Anantapur" },
          { title: "Chittoor" },
          { title: "East Godavari" },
          { title: "Guntur" },
          { title: "Krishna" },
          { title: "Kurnool" },
          { title: "Nellore" },
          { title: "Prakasam" },
          { title: "Srikakulam" },
          { title: "Visakhapatnam" },
          { title: "Vizianagaram" },
          { title: "West Godavari" },
          { title: "YSR Kadapa" },
        ],
      },
      {
        title: "Arunachal Pradesh",
        children: [
          { title: "Tawang" },
          { title: "West Kameng" },
          { title: "East Kameng" },
          { title: "Papum Pare" },
          { title: "Kurung Kumey" },
          { title: "Kra Daadi" },
          { title: "Lower Subansiri" },
          { title: "Upper Subansiri" },
          { title: "West Siang" },
          { title: "East Siang" },
          { title: "Siang" },
          { title: "Upper Siang" },
          { title: "Lower Siang" },
          { title: "Lower Dibang Valley" },
          { title: "Dibang Valley" },
          { title: "Anjaw" },
          { title: "Lohit" },
          { title: "Namsai" },
          { title: "Changlang" },
          { title: "Tirap" },
          { title: "Longding" },
        ],
      },
      {
        title: "Assam",
        children: [
          { title: "Baksa" },
          { title: "Barpeta" },
          { title: "Biswanath" },
          { title: "Bongaigaon" },
          { title: "Cachar" },
          { title: "Charaideo" },
          { title: "Chirang" },
          { title: "Darrang" },
          { title: "Dhemaji" },
          { title: "Dhubri" },
          { title: "Dibrugarh" },
          { title: "Goalpara" },
          { title: "Golaghat" },
          { title: "Hailakandi" },
          { title: "Hojai" },
          { title: "Jorhat" },
          { title: "Kamrup Metropolitan" },
          { title: "Kamrup" },
          { title: "Karbi Anglong" },
          { title: "Karimganj" },
          { title: "Kokrajhar" },
          { title: "Lakhimpur" },
          { title: "Majuli" },
          { title: "Morigaon" },
          { title: "Nagaon" },
          { title: "Nalbari" },
          { title: "Dima Hasao" },
          { title: "Sivasagar" },
          { title: "Sonitpur" },
          { title: "South Salmara-Mankachar" },
          { title: "Tinsukia" },
          { title: "Udalguri" },
          { title: "West Karbi Anglong" },
        ],
      },
      {
        title: "Bihar",
        children: [
          { title: "Araria" },
          { title: "Arwal" },
          { title: "Aurangabad" },
          { title: "Banka" },
          { title: "Begusarai" },
          { title: "Bhagalpur" },
          { title: "Bhojpur" },
          { title: "Buxar" },
          { title: "Darbhanga" },
          { title: "East Champaran (Motihari)" },
          { title: "Gaya" },
          { title: "Gopalganj" },
          { title: "Jamui" },
          { title: "Jehanabad" },
          { title: "Kaimur (Bhabua)" },
          { title: "Katihar" },
          { title: "Khagaria" },
          { title: "Kishanganj" },
          { title: "Lakhisarai" },
          { title: "Madhepura" },
          { title: "Madhubani" },
          { title: "Munger (Monghyr)" },
          { title: "Muzaffarpur" },
          { title: "Nalanda" },
          { title: "Nawada" },
          { title: "Patna" },
          { title: "Purnia (Purnea)" },
          { title: "Rohtas" },
          { title: "Saharsa" },
          { title: "Samastipur" },
          { title: "Saran" },
          { title: "Sheikhpura" },
          { title: "Sheohar" },
          { title: "Sitamarhi" },
          { title: "Siwan" },
          { title: "Supaul" },
          { title: "Vaishali" },
          { title: "West Champaran" },
        ],
      },
      {
        title: "Chandigarh (UT)",
        children: [{ title: "Chandigarh" }],
      },
      {
        title: "Chhattisgarh",
        children: [
          { title: "Balod" },
          { title: "Baloda Bazar" },
          { title: "Balrampur" },
          { title: "Bastar" },
          { title: "Bemetara" },
          { title: "Bijapur" },
          { title: "Bilaspur" },
          { title: "Dantewada (South Bastar)" },
          { title: "Dhamtari" },
          { title: "Durg" },
          { title: "Gariyaband" },
          { title: "Janjgir-Champa" },
          { title: "Jashpur" },
          { title: "Kabirdham (Kawardha)" },
          { title: "Kanker (North Bastar)" },
          { title: "Kondagaon" },
          { title: "Korba" },
          { title: "Korea (Koriya)" },
          { title: "Mahasamund" },
          { title: "Mungeli" },
          { title: "Narayanpur" },
          { title: "Raigarh" },
          { title: "Raipur" },
          { title: "Rajnandgaon" },
          { title: "Sukma" },
          { title: "Surajpur" },
          { title: "Surguja" },
        ],
      },
      {
        title: "Dadra and Nagar Haveli (UT)",
        children: [{ title: "Dadra & Nagar Haveli" }],
      },
      {
        title: "Daman and Diu (UT)",
        children: [{ title: "Daman" }, { title: "Diu" }],
      },
      {
        title: "Delhi (NCT)",
        children: [
          { title: "Central Delhi" },
          { title: "East Delhi" },
          { title: "New Delhi" },
          { title: "North Delhi" },
          { title: "North East  Delhi" },
          { title: "North West  Delhi" },
          { title: "Shahdara" },
          { title: "South Delhi" },
          { title: "South East Delhi" },
          { title: "South West  Delhi" },
          { title: "West Delhi" },
        ],
      },
      {
        title: "Goa",
        children: [{ title: "North Goa" }, { title: "South Goa" }],
      },
      {
        title: "Gujarat",
        children: [
          { title: "Ahmedabad" },
          { title: "Amreli" },
          { title: "Anand" },
          { title: "Aravalli" },
          { title: "Banaskantha (Palanpur)" },
          { title: "Bharuch" },
          { title: "Bhavnagar" },
          { title: "Botad" },
          { title: "Chhota Udepur" },
          { title: "Dahod" },
          { title: "Dangs (Ahwa)" },
          { title: "Devbhoomi Dwarka" },
          { title: "Gandhinagar" },
          { title: "Gir Somnath" },
          { title: "Jamnagar" },
          { title: "Junagadh" },
          { title: "Kachchh" },
          { title: "Kheda (Nadiad)" },
          { title: "Mahisagar" },
          { title: "Mehsana" },
          { title: "Morbi" },
          { title: "Narmada (Rajpipla)" },
          { title: "Navsari" },
          { title: "Panchmahal (Godhra)" },
          { title: "Patan" },
          { title: "Porbandar" },
          { title: "Rajkot" },
          { title: "Sabarkantha (Himmatnagar)" },
          { title: "Surat" },
          { title: "Surendranagar" },
          { title: "Tapi (Vyara)" },
          { title: "Vadodara" },
          { title: "Valsad" },
        ],
      },
      {
        title: "Haryana",
        children: [
          { title: "Ambala" },
          { title: "Bhiwani" },
          { title: "Charkhi Dadri" },
          { title: "Faridabad" },
          { title: "Fatehabad" },
          { title: "Gurgaon" },
          { title: "Hisar" },
          { title: "Jhajjar" },
          { title: "Jind" },
          { title: "Kaithal" },
          { title: "Karnal" },
          { title: "Kurukshetra" },
          { title: "Mahendragarh" },
          { title: "Mewat" },
          { title: "Palwal" },
          { title: "Panchkula" },
          { title: "Panipat" },
          { title: "Rewari" },
          { title: "Rohtak" },
          { title: "Sirsa" },
          { title: "Sonipat" },
          { title: "Yamunanagar" },
        ],
      },
      {
        title: "Himachal Pradesh",
        children: [
          { title: "Bilaspur" },
          { title: "Chamba" },
          { title: "Hamirpur" },
          { title: "Kangra" },
          { title: "Kinnaur" },
          { title: "Kullu" },
          { title: "Lahaul &amp; Spiti" },
          { title: "Mandi" },
          { title: "Shimla" },
          { title: "Sirmaur (Sirmour)" },
          { title: "Solan" },
          { title: "Una" },
        ],
      },
      {
        title: "Jammu and Kashmir",
        children: [
          { title: "Anantnag" },
          { title: "Bandipore" },
          { title: "Baramulla" },
          { title: "Budgam" },
          { title: "Doda" },
          { title: "Ganderbal" },
          { title: "Jammu" },
          { title: "Kargil" },
          { title: "Kathua" },
          { title: "Kishtwar" },
          { title: "Kulgam" },
          { title: "Kupwara" },
          { title: "Leh" },
          { title: "Poonch" },
          { title: "Pulwama" },
          { title: "Rajouri" },
          { title: "Ramban" },
          { title: "Reasi" },
          { title: "Samba" },
          { title: "Shopian" },
          { title: "Srinagar" },
          { title: "Udhampur" },
        ],
      },
      {
        title: "Jharkhand",
        children: [
          { title: "Bokaro" },
          { title: "Chatra" },
          { title: "Deoghar" },
          { title: "Dhanbad" },
          { title: "Dumka" },
          { title: "East Singhbhum" },
          { title: "Garhwa" },
          { title: "Giridih" },
          { title: "Godda" },
          { title: "Gumla" },
          { title: "Hazaribag" },
          { title: "Jamtara" },
          { title: "Khunti" },
          { title: "Koderma" },
          { title: "Latehar" },
          { title: "Lohardaga" },
          { title: "Pakur" },
          { title: "Palamu" },
          { title: "Ramgarh" },
          { title: "Ranchi" },
          { title: "Sahibganj" },
          { title: "Seraikela-Kharsawan" },
          { title: "Simdega" },
          { title: "West Singhbhum" },
        ],
      },
      {
        title: "Karnataka",
        children: [
          { title: "Bagalkot" },
          { title: "Ballari (Bellary)" },
          { title: "Belagavi (Belgaum)" },
          { title: "Bengaluru (Bangalore) Rural" },
          { title: "Bengaluru (Bangalore) Urban" },
          { title: "Bidar" },
          { title: "Chamarajanagar" },
          { title: "Chikballapur" },
          { title: "Chikkamagaluru (Chikmagalur)" },
          { title: "Chitradurga" },
          { title: "Dakshina Kannada" },
          { title: "Davangere" },
          { title: "Dharwad" },
          { title: "Gadag" },
          { title: "Hassan" },
          { title: "Haveri" },
          { title: "Kalaburagi (Gulbarga)" },
          { title: "Kodagu" },
          { title: "Kolar" },
          { title: "Koppal" },
          { title: "Mandya" },
          { title: "Mysuru (Mysore)" },
          { title: "Raichur" },
          { title: "Ramanagara" },
          { title: "Shivamogga (Shimoga)" },
          { title: "Tumakuru (Tumkur)" },
          { title: "Udupi" },
          { title: "Uttara Kannada (Karwar)" },
          { title: "Vijayapura (Bijapur)" },
          { title: "Yadgir" },
        ],
      },
      {
        title: "Kerala",
        children: [
          { title: "Alappuzha" },
          { title: "Ernakulam" },
          { title: "Idukki" },
          { title: "Kannur" },
          { title: "Kasaragod" },
          { title: "Kollam" },
          { title: "Kottayam" },
          { title: "Kozhikode" },
          { title: "Malappuram" },
          { title: "Palakkad" },
          { title: "Pathanamthitta" },
          { title: "Thiruvananthapuram" },
          { title: "Thrissur" },
          { title: "Wayanad" },
        ],
      },
      {
        title: "Lakshadweep (UT)",
        children: [
          { title: "Agatti" },
          { title: "Amini" },
          { title: "Androth" },
          { title: "Bithra" },
          { title: "Chethlath" },
          { title: "Kavaratti" },
          { title: "Kadmath" },
          { title: "Kalpeni" },
          { title: "Kilthan" },
          { title: "Minicoy" },
        ],
      },
      {
        title: "Madhya Pradesh",
        children: [
          { title: "Agar Malwa" },
          { title: "Alirajpur" },
          { title: "Anuppur" },
          { title: "Ashoknagar" },
          { title: "Balaghat" },
          { title: "Barwani" },
          { title: "Betul" },
          { title: "Bhind" },
          { title: "Bhopal" },
          { title: "Burhanpur" },
          { title: "Chhatarpur" },
          { title: "Chhindwara" },
          { title: "Damoh" },
          { title: "Datia" },
          { title: "Dewas" },
          { title: "Dhar" },
          { title: "Dindori" },
          { title: "Guna" },
          { title: "Gwalior" },
          { title: "Harda" },
          { title: "Hoshangabad" },
          { title: "Indore" },
          { title: "Jabalpur" },
          { title: "Jhabua" },
          { title: "Katni" },
          { title: "Khandwa" },
          { title: "Khargone" },
          { title: "Mandla" },
          { title: "Mandsaur" },
          { title: "Morena" },
          { title: "Narsinghpur" },
          { title: "Neemuch" },
          { title: "Panna" },
          { title: "Raisen" },
          { title: "Rajgarh" },
          { title: "Ratlam" },
          { title: "Rewa" },
          { title: "Sagar" },
          { title: "Satna" },
          { title: "Sehore" },
          { title: "Seoni" },
          { title: "Shahdol" },
          { title: "Shajapur" },
          { title: "Sheopur" },
          { title: "Shivpuri" },
          { title: "Sidhi" },
          { title: "Singrauli" },
          { title: "Tikamgarh" },
          { title: "Ujjain" },
          { title: "Umaria" },
          { title: "Vidisha" },
        ],
      },
      {
        title: "Maharashtra",
        children: [
          { title: "Ahmednagar" },
          { title: "Akola" },
          { title: "Amravati" },
          { title: "Aurangabad" },
          { title: "Beed" },
          { title: "Bhandara" },
          { title: "Buldhana" },
          { title: "Chandrapur" },
          { title: "Dhule" },
          { title: "Gadchiroli" },
          { title: "Gondia" },
          { title: "Hingoli" },
          { title: "Jalgaon" },
          { title: "Jalna" },
          { title: "Kolhapur" },
          { title: "Latur" },
          { title: "Mumbai City" },
          { title: "Mumbai Suburban" },
          { title: "Nagpur" },
          { title: "Nanded" },
          { title: "Nandurbar" },
          { title: "Nashik" },
          { title: "Osmanabad" },
          { title: "Palghar" },
          { title: "Parbhani" },
          { title: "Pune" },
          { title: "Raigad" },
          { title: "Ratnagiri" },
          { title: "Sangli" },
          { title: "Satara" },
          { title: "Sindhudurg" },
          { title: "Solapur" },
          { title: "Thane" },
          { title: "Wardha" },
          { title: "Washim" },
          { title: "Yavatmal" },
        ],
      },
      {
        title: "Manipur",
        children: [
          { title: "Bishnupur" },
          { title: "Chandel" },
          { title: "Churachandpur" },
          { title: "Imphal East" },
          { title: "Imphal West" },
          { title: "Jiribam" },
          { title: "Kakching" },
          { title: "Kamjong" },
          { title: "Kangpokpi" },
          { title: "Noney" },
          { title: "Pherzawl" },
          { title: "Senapati" },
          { title: "Tamenglong" },
          { title: "Tengnoupal" },
          { title: "Thoubal" },
          { title: "Ukhrul" },
        ],
      },
      {
        title: "Meghalaya",
        children: [
          { title: "East Garo Hills" },
          { title: "East Jaintia Hills" },
          { title: "East Khasi Hills" },
          { title: "North Garo Hills" },
          { title: "Ri Bhoi" },
          { title: "South Garo Hills" },
          { title: "South West Garo Hills " },
          { title: "South West Khasi Hills" },
          { title: "West Garo Hills" },
          { title: "West Jaintia Hills" },
          { title: "West Khasi Hills" },
        ],
      },
      {
        title: "Mizoram",
        children: [
          { title: "Aizawl" },
          { title: "Champhai" },
          { title: "Kolasib" },
          { title: "Lawngtlai" },
          { title: "Lunglei" },
          { title: "Mamit" },
          { title: "Saiha" },
          { title: "Serchhip" },
        ],
      },
      {
        title: "Nagaland",
        children: [
          { title: "Dimapur" },
          { title: "Kiphire" },
          { title: "Kohima" },
          { title: "Longleng" },
          { title: "Mokokchung" },
          { title: "Mon" },
          { title: "Peren" },
          { title: "Phek" },
          { title: "Tuensang" },
          { title: "Wokha" },
          { title: "Zunheboto" },
        ],
      },
      {
        title: "Odisha",
        children: [
          { title: "Angul" },
          { title: "Balangir" },
          { title: "Balasore" },
          { title: "Bargarh" },
          { title: "Bhadrak" },
          { title: "Boudh" },
          { title: "Cuttack" },
          { title: "Deogarh" },
          { title: "Dhenkanal" },
          { title: "Gajapati" },
          { title: "Ganjam" },
          { title: "Jagatsinghapur" },
          { title: "Jajpur" },
          { title: "Jharsuguda" },
          { title: "Kalahandi" },
          { title: "Kandhamal" },
          { title: "Kendrapara" },
          { title: "Kendujhar (Keonjhar)" },
          { title: "Khordha" },
          { title: "Koraput" },
          { title: "Malkangiri" },
          { title: "Mayurbhanj" },
          { title: "Nabarangpur" },
          { title: "Nayagarh" },
          { title: "Nuapada" },
          { title: "Puri" },
          { title: "Rayagada" },
          { title: "Sambalpur" },
          { title: "Sonepur" },
          { title: "Sundargarh" },
        ],
      },
      {
        title: "Puducherry (UT)",
        children: [
          { title: "Karaikal" },
          { title: "Mahe" },
          { title: "Pondicherry" },
          { title: "Yanam" },
        ],
      },
      {
        title: "Punjab",
        children: [
          { title: "Amritsar" },
          { title: "Barnala" },
          { title: "Bathinda" },
          { title: "Faridkot" },
          { title: "Fatehgarh Sahib" },
          { title: "Fazilka" },
          { title: "Ferozepur" },
          { title: "Gurdaspur" },
          { title: "Hoshiarpur" },
          { title: "Jalandhar" },
          { title: "Kapurthala" },
          { title: "Ludhiana" },
          { title: "Mansa" },
          { title: "Moga" },
          { title: "Muktsar" },
          { title: "Nawanshahr (Shahid Bhagat Singh Nagar)" },
          { title: "Pathankot" },
          { title: "Patiala" },
          { title: "Rupnagar" },
          { title: "Sahibzada Ajit Singh Nagar (Mohali)" },
          { title: "Sangrur" },
          { title: "Tarn Taran" },
        ],
      },
      {
        title: "Rajasthan",
        children: [
          { title: "Ajmer" },
          { title: "Alwar" },
          { title: "Banswara" },
          { title: "Baran" },
          { title: "Barmer" },
          { title: "Bharatpur" },
          { title: "Bhilwara" },
          { title: "Bikaner" },
          { title: "Bundi" },
          { title: "Chittorgarh" },
          { title: "Churu" },
          { title: "Dausa" },
          { title: "Dholpur" },
          { title: "Dungarpur" },
          { title: "Hanumangarh" },
          { title: "Jaipur" },
          { title: "Jaisalmer" },
          { title: "Jalore" },
          { title: "Jhalawar" },
          { title: "Jhunjhunu" },
          { title: "Jodhpur" },
          { title: "Karauli" },
          { title: "Kota" },
          { title: "Nagaur" },
          { title: "Pali" },
          { title: "Pratapgarh" },
          { title: "Rajsamand" },
          { title: "Sawai Madhopur" },
          { title: "Sikar" },
          { title: "Sirohi" },
          { title: "Sri Ganganagar" },
          { title: "Tonk" },
          { title: "Udaipur" },
        ],
      },
      {
        title: "Sikkim",
        children: [
          { title: "East Sikkim" },
          { title: "North Sikkim" },
          { title: "South Sikkim" },
          { title: "West Sikkim" },
        ],
      },
      {
        title: "Tamil Nadu",
        children: [
          { title: "Ariyalur" },
          { title: "Chennai" },
          { title: "Coimbatore" },
          { title: "Cuddalore" },
          { title: "Dharmapuri" },
          { title: "Dindigul" },
          { title: "Erode" },
          { title: "Kanchipuram" },
          { title: "Kanyakumari" },
          { title: "Karur" },
          { title: "Krishnagiri" },
          { title: "Madurai" },
          { title: "Nagapattinam" },
          { title: "Namakkal" },
          { title: "Nilgiris" },
          { title: "Perambalur" },
          { title: "Pudukkottai" },
          { title: "Ramanathapuram" },
          { title: "Salem" },
          { title: "Sivaganga" },
          { title: "Thanjavur" },
          { title: "Theni" },
          { title: "Thoothukudi (Tuticorin)" },
          { title: "Tiruchirappalli" },
          { title: "Tirunelveli" },
          { title: "Tiruppur" },
          { title: "Tiruvallur" },
          { title: "Tiruvannamalai" },
          { title: "Tiruvarur" },
          { title: "Vellore" },
          { title: "Viluppuram" },
          { title: "Virudhunagar" },
        ],
      },
      {
        title: "Telangana",
        children: [
          { title: "Adilabad" },
          { title: "Bhadradri Kothagudem" },
          { title: "Hyderabad" },
          { title: "Jagtial" },
          { title: "Jangaon" },
          { title: "Jayashankar Bhoopalpally" },
          { title: "Jogulamba Gadwal" },
          { title: "Kamareddy" },
          { title: "Karimnagar" },
          { title: "Khammam" },
          { title: "Komaram Bheem Asifabad" },
          { title: "Mahabubabad" },
          { title: "Mahabubnagar" },
          { title: "Mancherial" },
          { title: "Medak" },
          { title: "Medchal" },
          { title: "Nagarkurnool" },
          { title: "Nalgonda" },
          { title: "Nirmal" },
          { title: "Nizamabad" },
          { title: "Peddapalli" },
          { title: "Rajanna Sircilla" },
          { title: "Rangareddy" },
          { title: "Sangareddy" },
          { title: "Siddipet" },
          { title: "Suryapet" },
          { title: "Vikarabad" },
          { title: "Wanaparthy" },
          { title: "Warangal (Rural)" },
          { title: "Warangal (Urban)" },
          { title: "Yadadri Bhuvanagiri" },
        ],
      },
      {
        title: "Tripura",
        children: [
          { title: "Dhalai" },
          { title: "Gomati" },
          { title: "Khowai" },
          { title: "North Tripura" },
          { title: "Sepahijala" },
          { title: "South Tripura" },
          { title: "Unakoti" },
          { title: "West Tripura" },
        ],
      },
      {
        title: "Uttarakhand",
        children: [
          { title: "Almora" },
          { title: "Bageshwar" },
          { title: "Chamoli" },
          { title: "Champawat" },
          { title: "Dehradun" },
          { title: "Haridwar" },
          { title: "Nainital" },
          { title: "Pauri Garhwal" },
          { title: "Pithoragarh" },
          { title: "Rudraprayag" },
          { title: "Tehri Garhwal" },
          { title: "Udham Singh Nagar" },
          { title: "Uttarkashi" },
        ],
      },
      {
        title: "Uttar Pradesh",
        children: [
          { title: "Agra" },
          { title: "Aligarh" },
          { title: "Allahabad" },
          { title: "Ambedkar Nagar" },
          { title: "Amethi (Chatrapati Sahuji Mahraj Nagar)" },
          { title: "Amroha (J.P. Nagar)" },
          { title: "Auraiya" },
          { title: "Azamgarh" },
          { title: "Baghpat" },
          { title: "Bahraich" },
          { title: "Ballia" },
          { title: "Balrampur" },
          { title: "Banda" },
          { title: "Barabanki" },
          { title: "Bareilly" },
          { title: "Basti" },
          { title: "Bhadohi" },
          { title: "Bijnor" },
          { title: "Budaun" },
          { title: "Bulandshahr" },
          { title: "Chandauli" },
          { title: "Chitrakoot" },
          { title: "Deoria" },
          { title: "Etah" },
          { title: "Etawah" },
          { title: "Faizabad" },
          { title: "Farrukhabad" },
          { title: "Fatehpur" },
          { title: "Firozabad" },
          { title: "Gautam Buddha Nagar" },
          { title: "Ghaziabad" },
          { title: "Ghazipur" },
          { title: "Gonda" },
          { title: "Gorakhpur" },
          { title: "Hamirpur" },
          { title: "Hapur (Panchsheel Nagar)" },
          { title: "Hardoi" },
          { title: "Hathras" },
          { title: "Jalaun" },
          { title: "Jaunpur" },
          { title: "Jhansi" },
          { title: "Kannauj" },
          { title: "Kanpur Dehat" },
          { title: "Kanpur Nagar" },
          { title: "Kanshiram Nagar (Kasganj)" },
          { title: "Kaushambi" },
          { title: "Kushinagar (Padrauna)" },
          { title: "Lakhimpur - Kheri" },
          { title: "Lalitpur" },
          { title: "Lucknow" },
          { title: "Maharajganj" },
          { title: "Mahoba" },
          { title: "Mainpuri" },
          { title: "Mathura" },
          { title: "Mau" },
          { title: "Meerut" },
          { title: "Mirzapur" },
          { title: "Moradabad" },
          { title: "Muzaffarnagar" },
          { title: "Pilibhit" },
          { title: "Pratapgarh" },
          { title: "RaeBareli" },
          { title: "Rampur" },
          { title: "Saharanpur" },
          { title: "Sambhal (Bhim Nagar)" },
          { title: "Sant Kabir Nagar" },
          { title: "Shahjahanpur" },
          { title: "Shamali (Prabuddh Nagar)" },
          { title: "Shravasti" },
          { title: "Siddharth Nagar" },
          { title: "Sitapur" },
          { title: "Sonbhadra" },
          { title: "Sultanpur" },
          { title: "Unnao" },
          { title: "Varanasi" },
        ],
      },
      {
        title: "West Bengal",
        children: [
          { title: "Alipurduar" },
          { title: "Bankura" },
          { title: "Birbhum" },
          { title: "Burdwan (Bardhaman)" },
          { title: "Cooch Behar" },
          { title: "Dakshin Dinajpur (South Dinajpur)" },
          { title: "Darjeeling" },
          { title: "Hooghly" },
          { title: "Howrah" },
          { title: "Jalpaiguri" },
          { title: "Kalimpong" },
          { title: "Kolkata" },
          { title: "Malda" },
          { title: "Murshidabad" },
          { title: "Nadia" },
          { title: "North 24 Parganas" },
          { title: "Paschim Medinipur (West Medinipur)" },
          { title: "Purba Medinipur (East Medinipur)" },
          { title: "Purulia" },
          { title: "South 24 Parganas" },
          { title: "Uttar Dinajpur (North Dinajpur)" },
        ],
      },
    ],
  },
]
